"""empty message

Revision ID: 72191ad5f269
Revises: 
Create Date: 2024-03-05 23:36:07.466594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72191ad5f269'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_hash', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_hash')

    # ### end Alembic commands ###
